### ISSUE TITLE
sample(Categorical) behaves poorly with VI

### ISSUE THREAD

**Issue by longouyang** [probmods/webppl#571] opened 2016-07-18 22:53 UTC
On f0a0894, I can't get this simple model, or any variations of it, to work:

```js
var alpha = Vector([1,1,1,1]);
var vs = ['a','b','c','d'];
var model = function() {
  var ps = ad.value(sample(Dirichlet({alpha: alpha}))).data;
  sample(Categorical({ps: ps, vs: vs}));
}

Infer({method: 'optimize', samples: 1, steps: 2}, model)
```

Though it does work if I use the lowercase helpers `dirichlet` and `categorical` and ditch the `ad.value(...).data` bit.

**Comment by dritchie** [comment] 2016-07-19 00:25
The difference in behavior is caused by the fact that `categorical` is actually not implemented in terms of `Categorical` but rather `Discrete` (see `header.wppl`). The mean-field VI backend is getting confused by the `vs` parameter (which isn't a scalar or a tensor, so it doesn't know what to do with it) and throwing an unhelpful error message.

To me, this raises the question of why we even have a `Categorical` distribution type. We didn't used to, and I think the implementation in terms of `Discrete` is perfectly fine. Is there something I'm missing here, @null-a?

Also: you definitely don't want to be explicitly calling `ad.value` or `.data` -- these things will break the flow of gradients in the program (if not worse errors).

**Comment by null-a** [comment] 2016-07-19 08:05
> To me, this raises the question of why we even have a Categorical distribution type. We didn't used to, and I think the implementation in terms of Discrete is perfectly fine.

I agree. See #397. 

> Also: you definitely don't want to be explicitly calling ad.value or .data

Yep. Other than the guide annotations, programs written for VI should look just like any other webppl programs. (And importantly should work with other inference algorithms, where guide will mostly be ignored.) If we have to reach into ad or tensor internals, then something has gone wrong.

**Comment by null-a** [comment] 2016-07-19 14:55
> the mean-field VI backend is getting confused by the vs parameter

Now #573.

I don't think there are any other outstanding problems here so I'll close this.

**Closed by null-a** 2016-07-19 14:55 UTC
Labels: variational

**Comment by longouyang** [comment] 2016-07-21 20:24
>> To me, this raises the question of why we even have a Categorical distribution type. We didn't used to, and I think the implementation in terms of Discrete is perfectly fine.

> I agree. See #397.

One argument for a Categorical type is that in some non-parametric models (e.g., Indian Buffet Process, I think) you might want an ERP that has a `vs` parameter because this `vs` is itself sampled.

For example:

```js
var listOfFeatures = randomSubset(allFeatures);
var dist = Categorical({ps: listOfFeatures, vs: dirichlet({alpha: Ones(listOfFeatures.length) })})
repeat(5, function() { sample(dist) })
```
