### ISSUE TITLE
clearer error when flip is given impossible argument

### ISSUE THREAD

**Issue by erindb** [probmods/webppl#467] opened 2016-05-27 20:37 UTC
When flip is given an argument greater than one, like this

    Infer({method: 'enumerate'}, function() {return flip(1.1);});

The following error is thrown, and it can be hard to find where in the code this corresponds to.

    AssertionError: Expected marginal distribution to be normalized.

It seems like we could check some of the primitive functions for acceptable parameters and point that out to the user.

For `flip(1.1)`, we could also interpret the parameter as 1, which is (I guess) what the sampling-based inference algorithms (e.g. I tried 'regjection' and 'MCMC' and they just returned true in 100% of the samples) are currently doing. We could also throw a clear error and/or warning consistently across inference algorithms.

**Comment by null-a** [comment] 2016-06-14 18:27
Closing this as I noticed it's a duplicate of #332.

**Closed by null-a** 2016-06-14 18:27 UTC
Labels: error handling
