### ISSUE TITLE
Mapping with builtin functions fails silently

### ISSUE THREAD

**Issue by jayelm** [probmods/webppl#577] opened 2016-07-20 19:28 UTC
The program

```js
map(JSON.stringify, [1, 2, 3])
```

1. doesn't stop executing in browser WebPPL
2. silently terminates the program on the command line, doesn't return anything, and gives no error message:

```console
$ webppl test.wppl
$
```

As @longouyang has told me, you need to wrap the builtin in a function for CPS transform (e.g. `function(x) { JSON.stringify(x) }`, but there's no warning/error when functions are used in this way.

**Comment by longouyang** [comment] 2016-07-21 22:52
For a function `f`, Javascript stores its arity as `f.length`.

We could modify `map` so that it checks that the arity of `f` is greater than 3 (the mapping function needs to take at least `s`, `k`, `a` as arguments) and throw an error if not.

@null-a does that sound kosher to you?

**Comment by null-a** [comment] 2016-07-22 09:46
> @null-a does that sound kosher to you?

I think this could only catch some cases. If the arity of `f` is less than 3 then we know it's not a webppl function, but when the arity is 3 or greater the function could be either JS or webppl. So  both `JSON.stringify.length === 3` and `trueF.length === 3`.

I'd also be nervous about having run time checks that depend on compiler internals, and the fact that we'd end up adding such checks to every higher order function. 

I think we need to consider this problem as part of a general re-think of the FFI. (#358)

This is a duplicate of #30. It looks like @jayelm is aware of the work-around, so I'll close this.

**Closed by null-a** 2016-07-22 09:46 UTC
