### ISSUE TITLE
Can't assign to nested fields of globalStore

### ISSUE THREAD

**Issue by longouyang** [probmods/webppl#721] opened 2016-12-03 01:35 UTC
e.g., 

```js
globalStore['x'] = {}
globalStore['x']['foo'] = 3 // => compile error
```

**Comment by null-a** [comment] 2016-12-03 09:48
In my mind, this is the [expected](http://docs.webppl.org/en/master/globalstore.html#introducing-the-global-store) behaviour. To make this work we'd need to deep copy the store when execution branches I think. See #60.

**Comment by longouyang** [comment] 2016-12-03 18:53
Ah, thanks for the explanation.

Is this the expected behavior because shallow copying is a more-obviously-correct approach? Or because shallow copying is what we happen to have right now?

**Comment by null-a** [comment] 2016-12-03 18:57
The latter.

**Comment by null-a** [comment] 2016-12-03 19:27
To expand on that a little... It /is/ what we happen to have right now, but for good reason I think. Deep copying by default would be very costly for programs that stick big objects in the store and don't modify them, and wouldn't give any benefit.

**Comment by null-a** [comment] 2016-12-05 08:43
@long I'm closing this since I believe it's duplicate of #60. As far as I know, the only reason to consider deep copying the store is to allow the kind of mutation you're interested in.

**Closed by null-a** 2016-12-05 08:43 UTC
