### ISSUE TITLE
Improve reliability of MAP

### ISSUE THREAD

**Issue by mhtess** [probmods/webppl#667] opened 2016-10-06 17:34 UTC
For a simple beta-binomial example, the visual results from rejection (via `viz.density(...)`) are highly consistent from run to run, but the MAP moves around dramatically

This may relate to #509 

``` js
var observerModel = function(){
  var weight = uniform(0, 1)
  var coinFlipper = Binomial({n:20, p:weight})
  observe(coinFlipper, 15)
  return weight
}

var opts = {method: "rejection", samples: 5000}
var posteriorBeliefs = Infer(opts, observerModel)
print("Maximum a posteriori value = " + posteriorBeliefs.MAP().val)
viz.density(posteriorBeliefs, {bounds: [0,1]})
```

**Comment by null-a** [comment] 2016-10-06 17:52
Yes, I think `MAP` is a misleading name for what this computes. (At least in some cases.) See #140.

**Comment by longouyang** [comment] 2016-10-06 23:01
Note that `viz.density` isn't a pure representation of the posterior -- it does density estimation on your samples before it visualizes. This is, more or less, adding another layer of inference.

This might also be a good time to point out that you shouldn't trust the density pictures too much if your posterior is non-smooth or multimodal or bounded. Density estimation is a hard problem and the standard approach, which we use, has many known pitfalls.

**Comment by null-a** [comment] 2017-01-03 14:41
I'm closing this since I think it's a duplicate of #140.

**Closed by null-a** 2017-01-03 14:41 UTC
