### ISSUE TITLE
Documentation for Distribution.support() lacking

### ISSUE THREAD

**Issue by ab-10** [probmods/webppl#937] opened 2020-12-08 10:28 UTC
Looking at the documentation I'm unable to understand for what distributions is `support()` defined.

For example the following works:

```
var b = Bernoulli({p: 0.5})
print("Possible values sampled from Bernoulli: " + b.support())

>>> Possible values sampled from Bernoulli: true,false
```

whereas the same on Gaussian distribution fails:

```
var g = Gaussian({mu: 5, sigma: 4})
print("Possible values sampled from Gaussian: " + g.support())
>>> g.support is not a function
```

**Comment by null-a** [comment] 2020-12-08 11:16
My recollection is that we use `support` in two main ways:

1. Distributions with finite support always have a `support` method that returns an array containing all elements over which the distribution is defined.
2. Distributions that have support over a bounded subset of the real line use `support` to indicate lower and/or upper bounds.

Other distributions (e.g. those with countable support, support over entire real line, multivariate distributions) likely don't implement the method.

Yes, this isn't documented, in-part because it's not clear this is part of the public API I think. I'll close this as a duplicate of #894, but happy to try to answer further questions if you have them.

**Closed as completed by null-a** 2020-12-08 11:16 UTC

**Comment by ab-10** [comment] 2020-12-08 11:22
Thanks for the quick response, I'll redirect further conversation to the
#894.
